### PR TITLE
Blacklist option and removed default omissions

### PR DESCRIPTION
**Pull request by chamini2**
Hey, @jamesdixon. Done with what we talked about in #71. Check it out when you can.

### CODE REVIEW

**Comment by chamini2** [comment]
I'm seeing the same error with the new bookshelf version. Should I set the version to be exactly `0.10.0`?

**Comment by jamesdixon** [comment]
@chamini2 I guess we should determine if it's actually an issue or not.

**Comment by jamesdixon** [comment]
Otherwise, looks great!

**Comment by jamesdixon** [comment]
@chamini2 interestingly enough, I just got bit by the exact issue we were solving. I was just trying to pass through `parentId` and it was disappearing 😄

**Comment by chamini2** [comment]
Should I merge and fix the bookshelf problem later?

**Comment by jamesdixon** [comment]
Fine by me!

**Comment by chamini2** [comment]
Ok, I figured it out. It's the serializer. SeyZ made a recent change that introduces `null` in non existent relations instead of not listing them [issue](https://github.com/SeyZ/jsonapi-serializer/issues/106), [commit](https://github.com/SeyZ/jsonapi-serializer/commit/97cbfed67abc8d54dc9958fc779dfb667f2ac563). I'll force the version 3.3.0 while SeyZ responds to the issue.

**Comment by jamesdixon** [comment]
@chamini2 he recently gave me access to the repo. That said, if you have a suggested fix and submit a PR, I'll merge it.

**Comment by SeyZ** [comment]
You're right, I introduced `null` in non existent attributes in the records. It avoids apps to preprocess the dataset before serialising through jsonapi-serializer.

**Comment by jamesdixon** [comment]
@SeyZ does the fix suggested by @jcao02 in jsonapi-serializer#106 meet the needs of both?

**Comment by SeyZ** [comment]
Hey @jamesdixon I keep the old behavior by default: ignoring the attribute to serialize if not present from the original dataset.

I also introduced the "nullIfMissing" option to set the missing attribute to null to have the new behavior 👍

**Comment by jamesdixon** [comment]
@chamini2 thoughts on @SeyZ fix?

Also, I started thinking about this PR this morning. I believe that we should exclude `id` by default as it's already included as part of the payload. I can see a case for everything else, but not for `id` potentially being included twice without user intervention. 

Thoughts?

**Comment by chamini2** [comment]
>@chamini2 thoughts on @SeyZ fix?

@jamesdixon, the fix works perfectly.

> Thoughts?

Well, it makes sense. Maybe not removing the attribute called `id`, but the `idAttribute` of the model, since the _identifier_ doesn't *have* to be called `id`.

**Comment by jamesdixon** [comment]
> Well, it makes sense. Maybe not removing the attribute called `id`, but the `idAttribute` of the model, since the _identifier_ doesn't **have** to be called `id`.

Good call. Completely agree 👍

**Comment by chamini2** [comment]
What about people wanting to keep the `idAttribute`? Should we consider this later?

**Comment by chamini2** [comment]
Yeah, you're right. I have a question: did you imagine that if someone passes `omitAttrs` it still excludes `idAttribute` or not?

**Comment by jamesdixon** [comment]
Yes, still excludes it.

**Comment by chamini2** [comment]
@jamesdixon, done with this. Merge it if you feel it's done, it not, let me know!

**Comment by jamesdixon** [comment]
@chamini2 nice work. thank you

release as 1.0.0-beta.6

**Pull request merged**
